import math

W = 960
H = 540
HUD_H = 52
FPS_RENDER = 60

INIT_POP = 200
MAX_POP = 8000

DOT_RADIUS_PX = 4  # fixed radius for all dots
MASS_MIN = 0.0
MASS_MAX = 2.0
STRENGTH_MIN = 1.0
STRENGTH_MAX = 1.0

ENERGY_PER_MASS = 50.0
ENERGY_DECAY_PER_TICK = 0.05

MAX_MOVE_PX = 12.0
MOVE_COST = 0.0175 #0.04

FOOD_ENERGY = 25.0
FOOD_SIZE_PX = 5
FOOD_SPAWN_RATE = 2.0
MAX_FOOD = 500

CORPSE_FRACTION = 1.0
CORPSE_FOOD_ENERGY = 25.0
CORPSE_SPREAD_PX = 10.0

INTERACT_RADIUS_PX = 10.0
ATTACK_PENALTY = 0.2

SEX_MIN_FRAC = 0.60
SEX_POST_FRAC = 0.10
SEX_OFFSPRING = 4
MUT_STD = 0.01

ASEX_OFFSPRING = 2
ASEX_TRIGGER_OVERFLOW = True

RECALL_BUFFER_SIZE = 100
RESTART_RANDOM_FRAC = 0.1

BALDWIN_ENABLED_DEFAULT = True
RL_LR = 2e-3
MODE_TEMPERATURE = 0.5

OBS_GRID_W = 96
OBS_GRID_H = 54
OBS_SAMPLE_N = 7
OBS_RANGE_PX = 40.0

HIDDEN1 = 16
HIDDEN2 = 32

# Inspector panel (right-side)
INSPECT_W = 150
INSPECT_PAD = 10
INSPECT_REFRESH_DIV = 1  # update inspector visuals every N rendered frames
PICK_RADIUS_PX = 10


# Boundary mode
# True: hard rectangular boundary. False: cyclic torus (wrap-around).
ENABLE_BOUNDARY = True
